name: test-weaver-stack

services:
  qdrant:
    image: qdrant/qdrant:v1.15.3
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT_LOG_LEVEL=${QDRANT_LOG_LEVEL:-INFO}
    restart: unless-stopped

  neo4j:
    image: neo4j:5.26.0
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH_FILE=/run/secrets/neo4j_auth
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
    volumes:
      - neo4j_data:/data
    secrets:
      - neo4j_auth
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  qdrant_data:
  neo4j_data:
  redis_data:

secrets:
  # Keep this file out of VCS. Contents must be: neo4j/<your-password>
  neo4j_auth:
    file: ./secrets/neo4j_auth.txt