hackathon:
  name: "Qdrant Hackathon 2025"
  project: "Intelligent Test Case Generator for Server-Driven UI"
  team: "MLB Innovation"
  
partners:
  - name: "Qdrant"
    use: "Vector storage and similarity search"
  - name: "CrewAI"
    use: "Multi-agent orchestration"
  - name: "Mistral AI"
    use: "LLM for test generation"
  - name: "Linkup"
    use: "External test pattern search"

mlb_integration:
  apps:
    - "MLB (iOS)"
    - "MLB (Android)"
  server_driven_ui_version: "1.0.0"
  components:
    - "Team Page"
    - "Browse Menu"
    - "Gameday"
    - "Scoreboard"

test_generation:
  strategies:
    - "Happy Path"
    - "Edge Cases"
    - "Error Handling"
    - "Performance"
    - "Accessibility"
  
  coverage_targets:
    unit: 80
    integration: 70
    e2e: 60